name: hipax_log
description: Aplicativo de logística da Hipax Tecnologia LTDA.
publish_to: 'none'

version: 1.20.2+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animate_do: ^3.1.2
  animated_flip_counter: ^0.2.6
  # ai_barcode: ^3.2.4
  # ai_barcode_scanner: ^3.4.1
  animations: ^2.0.8
  animated_splash_screen: ^1.3.0
  blobs: ^2.0.0
  cloud_functions: ^4.4.1
  cloud_firestore: ^4.9.2
  date_field: ^3.0.5
  datetime_picker_formfield_new: ^2.1.0
  date_format: ^2.0.7
  expandable: ^5.0.1
  expansion_tile_card: ^3.0.0
  firebase_messaging: ^14.6.8
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  firebase_core: ^2.16.0
  flare_flutter: ^3.0.2
  flutter_feather_icons: ^2.0.0+1
  flutter_signature_pad: ^3.0.1
  flutter_google_maps_webservices: ^1.1.1
  fl_chart: ^0.63.0
  flutter_barcode_scanner: ^2.0.0
  flutter_spinkit: ^5.2.0
  focused_menu: ^1.0.5
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.1.0
  google_places_flutter_api: ^1.0.2
  grouped_list: ^5.1.2
  http: ^1.1.0
  intl: ^0.18.1
  introduction_screen: ^3.1.11
  image_picker: ^1.0.4
  im_stepper: ^1.0.1+1
  line_awesome_flutter: ^2.0.0
  mask_text_input_formatter: ^2.5.0
  open_file: ^3.3.2
  overlay_support: ^2.1.0
  oktoast: ^3.3.2
  percent_indicator: ^4.2.3
  printing: ^5.11.0
  provider: ^6.0.5
  pdf: ^3.10.4
  permission_handler: ^11.0.0
  page_route_transition: ^3.1.2
  page_transition: ^2.1.0
  qr_code_scanner: ^1.0.1
  rolling_switch: ^0.0.2
  rive: ^0.11.17
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.2.1
  status_alert: ^1.0.1
  sleek_circular_slider: ^2.0.1
  searchable_listview: ^2.7.0
  syncfusion_flutter_charts: ^23.1.38
  syncfusion_flutter_xlsio: ^23.1.38
  timeline_tile: ^2.0.0
  toast: ^0.3.0
  table_calendar: ^3.0.9
  toggle_switch: ^2.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.1.14
  vibration: ^1.8.2
  webview_flutter: ^4.4.0
  whatsapp_unilink: ^2.1.0
  google_api_headers: ^2.0.2
  path_provider: ^2.1.1
  # line_icons: ^2.0.3
  # avatar_glow: ^2.0.2
  # cupertino_icons: ^1.0.6
  # confetti: ^0.7.0
  # firebase_core_platform_interface: ^4.8.0
  # firebase_auth_platform_interface: ^6.19.0
  # firebase_auth_web: ^5.8.1
  # flutter_styled_toast: ^2.2.1
  # flutter_launcher_icons: ^0.13.1
  # firebase_storage_web: ^3.6.7
  # flutter_fortune_wheel: ^1.3.0
  # flutter_overboard: ^3.1.1
  # flutter_slidable: ^3.0.0
  # fluttertoast: ^8.2.2
  # flare_flutter: ^3.0.2
  # flutter_windowmanager: ^0.2.0
  # http_parser: ^4.0.2
  # html: ^0.15.4
  # modal_bottom_sheet: ^2.1.2
  # route_transitions: ^2.0.1
  # sliding_sheet: ^0.5.2
  # screenshot: ^2.1.0
  # timer_count_down: ^2.2.2
  # timeline_list: ^0.0.6
  # timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/

#flutter_icons:
#  android: 'launcher_icon'
#  ios: true
#  image_path: "lib/assets/icon.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: IconesHipaxNew
  #     fonts:
  #       - asset: lib/icon/IconesHipaxNew.ttf
  #   - family: MyFlutterAdd
  #     fonts:
  #       - asset: lib/icon/MyFlutterAdd.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages